In [1]:
# imports

import pandas as pd
import json

In [2]:
df1 = pd.read_csv('nextbrain_L_vols.csv', sep = ',')
df2 = pd.read_csv('nextbrain_R_vols.csv', sep = ',')
df3 = pd.read_csv('other_info.csv', sep = ',')

In [3]:
columnes = df2.columns.tolist()
dfNextbrain = df2.copy()

print(dfNextbrain.shape)
print(dfNextbrain['subject'].nunique())

for col in columnes:
    if col != 'subject':
        dfNextbrain[col] = df1[col] + df2[col] # El nou dataset tindrà els volums sumats

# Eliminem ja unes quantes columnes innecessàries
dfNextbrain = dfNextbrain.drop(columns = ['Unnamed: 0', 'session'])

(696, 267)
696

In [4]:
# comprovem el df
dfNextbrain.head()

,white_matter_of_forebrain,head_of_caudate,anterior_horn_of_lateral_ventricle,septum_pellucidum,putamen,anterior_olfactory_nucleus,olfactory_tubercle,core_of_nucleus_accumbens,claustrum,medial_septal_nucleus,...,ctx-rh-rostralmiddlefrontal,ctx-rh-superiorfrontal,ctx-rh-superiorparietal,ctx-rh-superiortemporal,ctx-rh-supramarginal,ctx-rh-frontalpole,ctx-rh-temporalpole,ctx-rh-transversetemporal,ctx-rh-insula,subject
0,278398.28,3768.3647,0.0,32.338490,7400.8084,39.511357,5.447924,578.36205,891.17356,159.821772,...,26590.814,28429.9755,20114.912,12486.3359,14155.4800,3011.5730,2296.3134,1081.99495,7312.6696,ADNI005S4910
1,343770.90,4935.5220,0.0,42.445020,8378.4175,43.793263,3.428122,709.72610,971.85806,243.211310,...,31693.463,41100.1800,24683.342,17687.1950,16659.7095,2987.8455,4278.1755,2085.70763,11737.2687,ADNI062S1294
2,402026.57,4418.4258,0.0,36.957087,9031.9649,52.365209,12.720504,885.94040,1295.58445,111.492286,...,36928.881,37361.1970,24990.472,21270.5780,16539.1240,5017.6204,3574.2878,1858.15327,13183.8275,ADNI130S4641
3,373729.27,4364.3825,0.0,27.096801,7718.5192,36.638529,7.318990,810.99310,1173.52320,159.203220,...,35624.983,35630.9450,25255.152,22887.9285,15886.7464,3240.7535,4491.6864,1476.50690,10233.7290,ADNI006S4363
4,392216.66,5197.9954,0.0,38.331591,9138.3733,71.053877,6.733125,761.79800,1184.80614,239.039040,...,29539.935,35985.3480,21040.731,20851.5360,18276.4280,3309.7693,3050.2209,1803.35761,13752.7309,ADNI002S1268

In [5]:
# Anem a crear  el df per les regions de l'hipocamp

# Obrim el diccionari
with open('AllenAtlasLUT_xtra.json', 'r') as f:
    lut_data = json.load(f)

# classes que pertanyen a l'hipocamp
CLASS_HI_IDS = [ 344, 369, 409, 567, 340, 563,
    419, 373, 572, 345, 370, 374,
    410, 420, 564, 573, 341, 568,
    371, 375, 411, 421, 565, 569,
    574, 342, 346, 326, 347, 576,
    558, 404, 364, 405, 559, 365,
    561, 407, 367, 575, 422, 432,
    320, 461, 343, 368, 372, 408, 418,
    562, 566, 571, 339, 354]

columnas_hi = []
for struct_id in CLASS_HI_IDS:
    str_id = str(struct_id)
    if str_id in lut_data:
        nombre_columna = lut_data[str_id]['labelName']
        if nombre_columna in dfNextbrain.columns:
            columnas_hi.append(nombre_columna)

if 'subject' in dfNextbrain.columns:
    df_hi = dfNextbrain[['subject'] + columnas_hi]
else:
    df_hi = dfNextbrain[columnas_hi]

In [6]:
# Mirem algunes dades del df que té les dades de nextBrain només de la regió de l'hipocamp

print(df_hi.shape)

df_hi.head()

(696, 55)

,subject,stratum_radiatum_of_rostral_ca1,stratum_radiatum_of_uncal_ca2,stratum_radiatum_of_rostral_ca2,stratum_radiatum_of_caudal_ca2,stratum_radiatum_of_uncal_ca1,stratum_radiatum_of_caudal_ca1,stratum_lucidum__of_rostral_ca3,stratum_lucidum__of_uncal_ca3,stratum_lucidum__of_caudal_ca3,...,stratum_lacunosum-moleculare_of_rostral_ca1,stratum_lacunosum-moleculare_of_uncal_ca2,stratum_lacunosum-moleculare_of_uncal_ca3,stratum_lacunosum-moleculare_of_rostral_ca2,stratum_lacunosum-moleculare_of_rostral_ca3,stratum_lacunosum-moleculare_of_caudal_ca1,stratum_lacunosum-moleculare_of_caudal_ca2,stratum_lacunosum-moleculare_of_caudal_ca3,stratum_lacunosum-moleculare_of_uncal_ca1,alveus
0,ADNI005S4910,152.802270,14.670469,7.362102,8.511515,42.281897,57.955465,18.052532,12.786324,7.706498,...,362.52515,39.685000,21.461066,37.026106,39.315497,90.430807,16.178908,18.235276,111.432037,374.50613
1,ADNI062S1294,248.266330,12.352503,5.765700,9.823310,43.710415,69.902808,12.000443,11.050981,9.084810,...,597.78467,36.964992,20.422351,29.207654,26.378427,115.526167,17.314140,22.269934,123.523130,493.68590
2,ADNI130S4641,165.592370,25.194663,10.368828,6.943167,56.442021,62.714768,19.459982,16.324059,6.513609,...,412.44357,43.589791,17.716035,20.074385,27.518516,123.850697,16.477653,16.685651,215.707490,610.14944
3,ADNI006S4363,199.479630,20.898382,9.844407,3.309592,50.930102,43.026745,18.729167,13.646025,3.915183,...,514.92982,57.471742,21.071737,37.227571,36.738037,84.976852,9.491794,10.238250,210.445475,625.50155
4,ADNI002S1268,200.677086,21.396131,10.667803,8.633143,52.282384,69.484355,24.178463,17.894348,8.142796,...,463.55106,44.679746,27.462933,42.740456,46.411553,105.921970,14.701635,15.906741,141.504615,497.16087

In [7]:
# Fem l'agrupació de columnes de l'hipocampus per reduir-ne el nombre

# Llista dels subcamps CA que volem agrupar
ca_subfields = ['ca1', 'ca2', 'ca3', 'ca4']

# Identificar quines columnes del fitxer original contenen algun CA
ca_cols = [col for col in df_hi.columns if any(ca in col.lower() for ca in ca_subfields)]

# Identificar les columnes que NO contenen CA (les que volem deixar com estan)
other_cols = [col for col in df_hi.columns if col not in ca_cols]

# Creem el nou DataFrame començant per les columnes que no canvien
new_df = df_hi[other_cols].copy()

# Per a cada subcamp CA, sumem totes les seves capes i regions en una sola columna
for ca in ca_subfields:
    # Seleccionem només les columnes d'aquest CA específic (ex: tot el que tingui 'ca1')
    target_cols = [col for col in df_hi.columns if ca in col.lower()]

    if target_cols:
        new_df[ca.upper()] = df_hi[target_cols].sum(axis=1)

# Reordenem per a que 'subject' sigui la primera columna si no ho era ja
cols = ['subject'] + [c for c in new_df.columns if c != 'subject']
new_df = new_df[cols]

In [8]:
# Anem a veure com ens queda finalment amb l'agrupament

print(new_df.shape)

new_df.head()

(696, 20)

,subject,uncal_subiculum,rostral_subiculum,caudal_subiculum,molecular_layer_of_caudal_dentate_gyrus,molecular_layer_of_rostral_dentate_gyrus,molecular_layer_of_uncal_dentate_gyrus,granular_layer_of_rostral_dentate_gyrus,granular_layer_of_caudal_dentate_gyrus,granular_layer_of_uncal_dentate_gyrus,polyform_layer_of_caudal_dentate_gyrus,polyform_layer_of_rostral_dentate_gyrus,polyform_layer_of_uncal_dentate_gyrus,amygdalohippocampal_transition_area,fimbria,alveus,CA1,CA2,CA3,CA4
0,ADNI005S4910,30.503677,768.99631,289.87733,107.367495,260.544545,38.360190,50.837618,26.756949,6.422810,53.741285,165.254580,21.276871,5.126280,85.921932,374.50613,1798.684416,209.878354,299.625402,135.551627
1,ADNI062S1294,32.907246,934.24064,378.48858,118.887238,306.530350,37.440156,57.931445,29.096118,6.408871,60.457125,183.864334,19.903575,4.012958,40.065542,493.68590,2595.487608,199.852093,253.475270,129.159325
2,ADNI130S4641,93.783352,1223.17330,382.22754,104.708494,261.793060,42.313500,49.340468,26.444156,7.179636,53.428646,167.645394,23.018986,19.507110,46.812466,610.14944,2231.725443,246.487767,287.313860,120.883731
3,ADNI006S4363,77.590414,1120.76971,289.51364,62.901214,316.440830,33.798224,63.559000,14.590159,5.829171,30.572877,214.280180,19.814757,20.116048,61.470137,625.50155,2333.453451,250.043211,287.512213,151.016430
4,ADNI002S1268,57.148195,1102.96660,348.96447,111.930649,333.230810,42.918029,65.742737,28.662113,6.837303,55.617495,206.866485,22.811389,10.704142,63.634976,497.16087,2292.735119,287.460292,392.576123,182.182700

In [9]:
# Anem ara a gestionar el df amb other info

df_relevant = df3[['abeta_pos', 'age', 'apoe4']]

In [10]:
# Afegim les columnes al nostre df net

df_resultado = pd.concat([new_df, df_relevant], axis=1)

# Comprovem aquest primer preprocés:
print(df_resultado.shape)

df_resultado.head()

# Ens el guardem
df_resultado.to_csv('df_hp_adni.csv', index=False, sep=',', encoding='utf-8')

(696, 23)

In [11]:
# mirem si hi ha nan
df_resultado.dropna(inplace=True)

print(df_resultado.shape)

(696, 23)